name: Deploy to GitHub-Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Installing Dependencies
        run: pnpm i

      - name: Building
        run: pnpm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./dist
          branch: gh-pages
